version: '3'

services:
  ssh:
    container_name: ssh
    working_dir: /main
    command: sh -c "cp -r /root/.ssh2/ /root/.ssh/ && chmod 0400 /root/.ssh/* && cd ~; sh"
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - /home/${USER}/.ssh:/root/.ssh2/:ro
